name: mockingbird
description: "A video/audio player for shadowing any language."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0-327.4.beta

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^5.3.1
  objectbox_flutter_libs: any
  path: ^1.9.1
  path_provider: ^2.1.5
  image_picker: ^1.2.2
  file_picker: ^8.1.2
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  objectbox_generator: any

flutter:
  uses-material-design: true
