// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/album.dart';
import 'model/media.dart';
import 'model/sentence.dart';
import 'model/subtitle.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7561125612899362134),
    name: 'Media',
    lastPropertyId: const obx_int.IdUid(5, 6056864184607403191),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2950971484890171344),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2970887111947828870),
        name: 'pathStr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5005286091902331027),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6056864184607403191),
        name: 'subtitleId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 5036695174582107481),
        relationField: 'subtitle',
        relationTarget: 'Subtitle',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 706679735308781074),
        name: 'albums',
        targetId: const obx_int.IdUid(6, 6109400686112909804),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7871170772057366465),
    name: 'Sentence',
    lastPropertyId: const obx_int.IdUid(5, 4688229675110530019),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2756859356960013404),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4348816439563618990),
        name: 'startMilliseconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7859161537347489575),
        name: 'endMilliseconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4966457835990661018),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4688229675110530019),
        name: 'subtitleId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 1020403847008999375),
        relationField: 'subtitle',
        relationTarget: 'Subtitle',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3497535288821823847),
    name: 'Subtitle',
    lastPropertyId: const obx_int.IdUid(2, 4611615002765150875),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6055081687868125622),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4611615002765150875),
        name: 'mediaId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 5898832665637527043),
        relationField: 'media',
        relationTarget: 'Media',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'sentences',
        srcEntity: 'Sentence',
        srcField: 'subtitle',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 6109400686112909804),
    name: 'Album',
    lastPropertyId: const obx_int.IdUid(4, 8309855470154231611),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 82910295688152652),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3667094355173884039),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1518802893302678615),
        name: 'coverPathStr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8309855470154231611),
        name: 'sortOrder',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(7, 8805827754050254520),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'medias',
        srcEntity: 'Media',
        srcField: 'albums',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 6109400686112909804),
    lastIndexId: const obx_int.IdUid(7, 8805827754050254520),
    lastRelationId: const obx_int.IdUid(1, 706679735308781074),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [9011113446969728974, 5796585602580892729],
    retiredIndexUids: const [6937227900520055071],
    retiredPropertyUids: const [
      2814719371012559683,
      4796821091185661977,
      8186777228611248890,
      5310317453726506904,
      7665466568446012272,
      4752569662415279250,
      7225881723818059437,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Media: obx_int.EntityDefinition<Media>(
      model: _entities[0],
      toOneRelations: (Media object) => [object.subtitle],
      toManyRelations: (Media object) => {
        obx_int.RelInfo<Media>.toMany(1, object.id): object.albums,
      },
      getId: (Media object) => object.id,
      setId: (Media object, int id) {
        object.id = id;
      },
      objectToFB: (Media object, fb.Builder fbb) {
        final pathStrOffset = fbb.writeString(object.pathStr);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(2, pathStrOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addInt64(4, object.subtitle.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final pathStrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = Media(
          pathStr: pathStrParam,
          name: nameParam,
          id: idParam,
        );
        object.subtitle.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.subtitle.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Media>(
          object.albums,
          store,
          obx_int.RelInfo<Media>.toMany(1, object.id),
        );
        return object;
      },
    ),
    Sentence: obx_int.EntityDefinition<Sentence>(
      model: _entities[1],
      toOneRelations: (Sentence object) => [object.subtitle],
      toManyRelations: (Sentence object) => {},
      getId: (Sentence object) => object.id,
      setId: (Sentence object, int id) {
        object.id = id;
      },
      objectToFB: (Sentence object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.startMilliseconds);
        fbb.addInt64(2, object.endMilliseconds);
        fbb.addOffset(3, textOffset);
        fbb.addInt64(4, object.subtitle.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final startMillisecondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final endMillisecondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = Sentence(
          startMilliseconds: startMillisecondsParam,
          endMilliseconds: endMillisecondsParam,
          text: textParam,
          id: idParam,
        );
        object.subtitle.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.subtitle.attach(store);
        return object;
      },
    ),
    Subtitle: obx_int.EntityDefinition<Subtitle>(
      model: _entities[2],
      toOneRelations: (Subtitle object) => [object.media],
      toManyRelations: (Subtitle object) => {
        obx_int.RelInfo<Sentence>.toOneBacklink(
          5,
          object.id,
          (Sentence srcObject) => srcObject.subtitle,
        ): object.sentences,
      },
      getId: (Subtitle object) => object.id,
      setId: (Subtitle object, int id) {
        object.id = id;
      },
      objectToFB: (Subtitle object, fb.Builder fbb) {
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.media.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = Subtitle(id: idParam);
        object.media.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.media.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Subtitle>(
          object.sentences,
          store,
          obx_int.RelInfo<Sentence>.toOneBacklink(
            5,
            object.id,
            (Sentence srcObject) => srcObject.subtitle,
          ),
        );
        return object;
      },
    ),
    Album: obx_int.EntityDefinition<Album>(
      model: _entities[3],
      toOneRelations: (Album object) => [],
      toManyRelations: (Album object) => {
        obx_int.RelInfo<Media>.toManyBacklink(1, object.id): object.medias,
      },
      getId: (Album object) => object.id,
      setId: (Album object, int id) {
        object.id = id;
      },
      objectToFB: (Album object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final coverPathStrOffset = object.coverPathStr == null
            ? null
            : fbb.writeString(object.coverPathStr!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, coverPathStrOffset);
        fbb.addInt64(3, object.sortOrder);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final coverPathStrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object = Album(
          name: nameParam,
          sortOrder: sortOrderParam,
          id: idParam,
          coverPathStr: coverPathStrParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<Album>(
          object.medias,
          store,
          obx_int.RelInfo<Media>.toManyBacklink(1, object.id),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Media] entity fields to define ObjectBox queries.
class Media_ {
  /// See [Media.id].
  static final id = obx.QueryIntegerProperty<Media>(_entities[0].properties[0]);

  /// See [Media.pathStr].
  static final pathStr = obx.QueryStringProperty<Media>(
    _entities[0].properties[1],
  );

  /// See [Media.name].
  static final name = obx.QueryStringProperty<Media>(
    _entities[0].properties[2],
  );

  /// See [Media.subtitle].
  static final subtitle = obx.QueryRelationToOne<Media, Subtitle>(
    _entities[0].properties[3],
  );

  /// see [Media.albums]
  static final albums = obx.QueryRelationToMany<Media, Album>(
    _entities[0].relations[0],
  );
}

/// [Sentence] entity fields to define ObjectBox queries.
class Sentence_ {
  /// See [Sentence.id].
  static final id = obx.QueryIntegerProperty<Sentence>(
    _entities[1].properties[0],
  );

  /// See [Sentence.startMilliseconds].
  static final startMilliseconds = obx.QueryIntegerProperty<Sentence>(
    _entities[1].properties[1],
  );

  /// See [Sentence.endMilliseconds].
  static final endMilliseconds = obx.QueryIntegerProperty<Sentence>(
    _entities[1].properties[2],
  );

  /// See [Sentence.text].
  static final text = obx.QueryStringProperty<Sentence>(
    _entities[1].properties[3],
  );

  /// See [Sentence.subtitle].
  static final subtitle = obx.QueryRelationToOne<Sentence, Subtitle>(
    _entities[1].properties[4],
  );
}

/// [Subtitle] entity fields to define ObjectBox queries.
class Subtitle_ {
  /// See [Subtitle.id].
  static final id = obx.QueryIntegerProperty<Subtitle>(
    _entities[2].properties[0],
  );

  /// See [Subtitle.media].
  static final media = obx.QueryRelationToOne<Subtitle, Media>(
    _entities[2].properties[1],
  );

  /// see [Subtitle.sentences]
  static final sentences = obx.QueryBacklinkToMany<Sentence, Subtitle>(
    Sentence_.subtitle,
  );
}

/// [Album] entity fields to define ObjectBox queries.
class Album_ {
  /// See [Album.id].
  static final id = obx.QueryIntegerProperty<Album>(_entities[3].properties[0]);

  /// See [Album.name].
  static final name = obx.QueryStringProperty<Album>(
    _entities[3].properties[1],
  );

  /// See [Album.coverPathStr].
  static final coverPathStr = obx.QueryStringProperty<Album>(
    _entities[3].properties[2],
  );

  /// See [Album.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<Album>(
    _entities[3].properties[3],
  );
}
