// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'db/entities/media_progress_entity.dart';
import 'db/entities/metadata_entity.dart';
import 'db/entities/preference_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 729033443109422583),
    name: 'PreferenceEntity',
    lastPropertyId: const obx_int.IdUid(5, 1294798852857759556),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3450668083517008733),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4461715936515113546),
        name: 'loop',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 5952320101620290434),
    name: 'MediaProgressEntity',
    lastPropertyId: const obx_int.IdUid(4, 5848876766913076143),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5964299288388099959),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4863690826892868589),
        name: 'mediaId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1033017535922868972),
        name: 'subtitleName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5848876766913076143),
        name: 'positionMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 504364132294857989),
    name: 'MetadataEntity',
    lastPropertyId: const obx_int.IdUid(13, 3798833145530129820),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6933474094506189213),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7707177243200400860),
        name: 'databaseVersion',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8767881914140223660),
        name: 'playingMediaId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3798833145530129820),
        name: 'permissionRequested',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 2586471359586555997),
        name: 'mediaProgressList',
        targetId: const obx_int.IdUid(6, 5952320101620290434),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(8, 504364132294857989),
    lastIndexId: const obx_int.IdUid(3, 3349414689770527415),
    lastRelationId: const obx_int.IdUid(1, 2586471359586555997),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      2126596270909047534,
      8902126513492675573,
      3499439688354918970,
      1008498112060179752,
      5174797425466321050,
    ],
    retiredIndexUids: const [326960807843455703, 3349414689770527415],
    retiredPropertyUids: const [
      2883212314392902367,
      3497499546518911977,
      4876908164482564772,
      1294798852857759556,
      7300803784323589485,
      2105834102041112161,
      3289810162652428670,
      1836310590922492628,
      7945704224739291284,
      7659414703713460585,
      5705690012012046614,
      904786334668511033,
      5152823660570640365,
      4107800010952606988,
      1437285181690893501,
      128390169501596559,
      307908795296079429,
      5806132384591857012,
      4271992074009824622,
      3475073127183216905,
      1543421011781232460,
      1315020076868800968,
      400750834343719344,
      1244199216946912259,
      8764957294575502160,
      1717180428108520633,
      5723628302721027830,
      6437877583935328934,
      2270843855102508589,
      7610656847973011315,
      1552733269508983676,
      5052697586594925986,
      6782397067082892659,
      3082450590266141572,
      3012435968327824577,
      6945451645110104092,
      1845871881868038950,
      2263419240791540139,
      3019313547298258536,
      5079920925565655168,
      9219390653332487671,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    PreferenceEntity: obx_int.EntityDefinition<PreferenceEntity>(
      model: _entities[0],
      toOneRelations: (PreferenceEntity object) => [],
      toManyRelations: (PreferenceEntity object) => {},
      getId: (PreferenceEntity object) => object.id,
      setId: (PreferenceEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PreferenceEntity object, fb.Builder fbb) {
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addBool(2, object.loop);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final loopParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final object = PreferenceEntity(id: idParam, loop: loopParam);

        return object;
      },
    ),
    MediaProgressEntity: obx_int.EntityDefinition<MediaProgressEntity>(
      model: _entities[1],
      toOneRelations: (MediaProgressEntity object) => [],
      toManyRelations: (MediaProgressEntity object) => {},
      getId: (MediaProgressEntity object) => object.id,
      setId: (MediaProgressEntity object, int id) {
        object.id = id;
      },
      objectToFB: (MediaProgressEntity object, fb.Builder fbb) {
        final mediaIdOffset = fbb.writeString(object.mediaId);
        final subtitleNameOffset = object.subtitleName == null
            ? null
            : fbb.writeString(object.subtitleName!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, mediaIdOffset);
        fbb.addOffset(2, subtitleNameOffset);
        fbb.addInt64(3, object.positionMs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final mediaIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final subtitleNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final positionMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = MediaProgressEntity(
          id: idParam,
          mediaId: mediaIdParam,
          subtitleName: subtitleNameParam,
          positionMs: positionMsParam,
        );

        return object;
      },
    ),
    MetadataEntity: obx_int.EntityDefinition<MetadataEntity>(
      model: _entities[2],
      toOneRelations: (MetadataEntity object) => [],
      toManyRelations: (MetadataEntity object) => {
        obx_int.RelInfo<MetadataEntity>.toMany(1, object.id):
            object.mediaProgressList,
      },
      getId: (MetadataEntity object) => object.id,
      setId: (MetadataEntity object, int id) {
        object.id = id;
      },
      objectToFB: (MetadataEntity object, fb.Builder fbb) {
        final playingMediaIdOffset = object.playingMediaId == null
            ? null
            : fbb.writeString(object.playingMediaId!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addInt64(10, object.databaseVersion);
        fbb.addOffset(11, playingMediaIdOffset);
        fbb.addBool(12, object.permissionRequested);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final playingMediaIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final databaseVersionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final permissionRequestedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          28,
          false,
        );
        final object = MetadataEntity(
          id: idParam,
          playingMediaId: playingMediaIdParam,
          databaseVersion: databaseVersionParam,
          permissionRequested: permissionRequestedParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<MetadataEntity>(
          object.mediaProgressList,
          store,
          obx_int.RelInfo<MetadataEntity>.toMany(1, object.id),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [PreferenceEntity] entity fields to define ObjectBox queries.
class PreferenceEntity_ {
  /// See [PreferenceEntity.id].
  static final id = obx.QueryIntegerProperty<PreferenceEntity>(
    _entities[0].properties[0],
  );

  /// See [PreferenceEntity.loop].
  static final loop = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[0].properties[1],
  );
}

/// [MediaProgressEntity] entity fields to define ObjectBox queries.
class MediaProgressEntity_ {
  /// See [MediaProgressEntity.id].
  static final id = obx.QueryIntegerProperty<MediaProgressEntity>(
    _entities[1].properties[0],
  );

  /// See [MediaProgressEntity.mediaId].
  static final mediaId = obx.QueryStringProperty<MediaProgressEntity>(
    _entities[1].properties[1],
  );

  /// See [MediaProgressEntity.subtitleName].
  static final subtitleName = obx.QueryStringProperty<MediaProgressEntity>(
    _entities[1].properties[2],
  );

  /// See [MediaProgressEntity.positionMs].
  static final positionMs = obx.QueryIntegerProperty<MediaProgressEntity>(
    _entities[1].properties[3],
  );
}

/// [MetadataEntity] entity fields to define ObjectBox queries.
class MetadataEntity_ {
  /// See [MetadataEntity.id].
  static final id = obx.QueryIntegerProperty<MetadataEntity>(
    _entities[2].properties[0],
  );

  /// See [MetadataEntity.databaseVersion].
  static final databaseVersion = obx.QueryIntegerProperty<MetadataEntity>(
    _entities[2].properties[1],
  );

  /// See [MetadataEntity.playingMediaId].
  static final playingMediaId = obx.QueryStringProperty<MetadataEntity>(
    _entities[2].properties[2],
  );

  /// See [MetadataEntity.permissionRequested].
  static final permissionRequested = obx.QueryBooleanProperty<MetadataEntity>(
    _entities[2].properties[3],
  );

  /// see [MetadataEntity.mediaProgressList]
  static final mediaProgressList =
      obx.QueryRelationToMany<MetadataEntity, MediaProgressEntity>(
        _entities[2].relations[0],
      );
}
